development:
  jobs_url: <%= (ENV["REDIS_URL"] || "redis://127.0.0.1:6379")%>/0
  cache_url: <%= (ENV["REDIS_URL"] || "redis://127.0.0.1:6379")%>/1
test:
  cache_url: <%= (ENV["REDIS_URL"] || "redis://127.0.0.1:6379")%>/15
production:
  jobs_url: <%= ENV['REDIS_URL'] %>/0
  cache_url: <%= ENV['REDIS_URL'] %>/1
